### ISSUE TITLE
selected text background invisible.

### ISSUE THREAD

**Issue by jpfairbanks** [josa42/atom-smyck#3]
Thanks for this great port!
When using this theme, I find that highlighting text does not show the region with a different background color. I thought that the color was being set at this line in syntax-variable.less. 

``` less
@syntax-selection-color: rgba(31, 182, 220, 0.39);
```

These lines in base.less appear relevant

``` less

  &.is-focused .selection .region {
    background-color: @syntax-selection-color;
  }

  &.is-focused .line-number.cursor-line-no-selection, &.is-focused .line.cursor-line {
    background-color: rgba(255, 255, 255, 0.1);
  }
```

My background color is sufficiently different from this color, that I should be able to see the selection. When I change to a different syntax theme the selected region background becomes visible.

Is anyone else unable to see the selected region when using this theme?

**Comment by jpfairbanks** [comment]
Of course as soon as I described the problem I was able to find a workaround by adding this to my styles.less file 

``` less
atom-text-editor::shadow .selection .region {
     background-color: @syntax-selection-color;
}
```

Hopefully it helps anyone else who runs into the issue.
